name: Build CLI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build & Test
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx
          pipx install poetry
          
          python -m venv .venv
          poetry build
          pip install -q --target pack --no-compile --upgrade dist/quber_cli-0.0.1-py3-none-any.whl
          python -m zipapp pack -o ./quber_cli.pyz --main=quber_cli.__main__:cli --compress

      - name: Upload zipapp
        uses: actions/upload-artifact@v4
        with:
          name: quber_cli.pyz
          path: quber_cli.pyz
