name: Test build process

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build & Test
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        pipx install poetry
        
        cd ./scripts
        source build_linux.sh
        ./test.sh
        ./validate.sh
